### ISSUE TITLE
video tutorial request

### ISSUE THREAD

**Issue by Dziban-dev** [Sunlitazure/ManeGen#1]
is there a video or written instructions on how the addon works?

**Comment by Sunlitazure** [comment]
I've been meaning to document this, so I'll write a README and/or make a video by Monday

**Comment by Sunlitazure** [comment]
A README has been added with detailed instructions on how to use ManeGen. If I make a video tutorial for this someday I will add the link to the README.

The script has now been officially released as ManeGen v1.0.

If you have any further issues or questions, open another Issue. I'm closing this Issue as completed.
